### ISSUE TITLE
setup.sh and the config file to download ID mapping databases should use FAIR...

### ISSUE THREAD

**Issue by egonw** [bridgedb/docker#13]
They now have ID mapping databases hardcoded, but in a future version, we should dynamically discover which ID mapping databases are the latest, using FAIR metadata from some source to be determined. This is not currently a blocker, as we can make new Docker versions for each big ID mapping database release without too much effort, based on (project) needs.

**Comment by Chris-Evelo** [comment]
We do produce VOID headers for the IMS linksets generated from these databases. I suppose these VOID headers already contain that info? Then we should just think of a mechanism to package that information

**Comment by egonw** [comment]
Implemented.
