### ISSUE TITLE
script needs updating

### ISSUE THREAD

**Issue by egonw** [bridgedb/docker#17]
This line no longer works (and will not again): https://github.com/bridgedb/docker/blob/335149b2cdb3b134b31d0d584fec2611f807cba7/setup.sh#L22

**Comment by marvinm2** [comment]
Why?

**Comment by marvinm2** [comment]
What needs to change?

**Comment by egonw** [comment]
Because the `/data/gene_databases/` no longer hosts the files, and only indexes them. Check the links for them, and you will see they are now downloaded from elsewhere.
