### ISSUE TITLE
 add dynamic download of mapping files

### ISSUE THREAD

**Issue by marvinm2** [bridgedb/docker#18]
https://chem-bla-ics.blogspot.com/2021/02/downloading-all-currently-released.html

**Comment by marvinm2** [comment]
Done for setup.sh
Now gdb.config should be made dynamically

**Comment by egonw** [comment]
Three files with `gdb.config` are now generated and added to the repo.

@marvinm2, can you please test it? E.g. http://bridgedb.github.io/data/other.json.config

**Comment by egonw** [comment]
Implemented.
