### ISSUE TITLE
the default web page for the docker should use Swagger

### ISSUE THREAD

**Issue by egonw** [bridgedb/docker#2]
And look something like:

![image](https://user-images.githubusercontent.com/26721/34227723-71f67106-e5ce-11e7-96da-b80ebf88d11a.png)

**Comment by marvinm2** [comment]
Nuno implemented this. Needs some configuration work but looks like this now.

![image](https://user-images.githubusercontent.com/26296100/39767057-13029e7e-52e6-11e8-9f15-6bd7e0b3b341.png)
