### ISSUE TITLE
hardcoded BridgeDb version in setup script

### ISSUE THREAD

**Issue by egonw** [bridgedb/docker#40]
https://github.com/bridgedb/docker/blob/db843f727bfcfc038eaa96f26c5d9e52dae90696/setup.sh#L7

I guess this should be discovered in a similar way as the Docker versioning is doing.

**Comment by jmillanacosta** [comment]
Working, see https://github.com/bridgedb/docker/commit/d0fd2e9137c06367e4c429b5ffa05f3ea87190f4 

The script is now pushed at every run if the version number changes
