### ISSUE TITLE
'latest' is not the latest

### ISSUE THREAD

**Issue by egonw** [bridgedb/docker#47]
No new Docker got created for [BridgeDb Webservice 2.1.7](https://github.com/bridgedb/BridgeDbWebservice/releases/tag/2.1.7).

**Comment by egonw** [comment]
@marvinm2, is that because of this line? https://github.com/bridgedb/docker/blob/master/setup.sh#L12

**Comment by jmillanacosta** [comment]
Solved with https://github.com/bridgedb/docker/commit/d0fd2e9137c06367e4c429b5ffa05f3ea87190f4
