### ISSUE TITLE
How to handle bridgedb versions?

### ISSUE THREAD

**Issue by nunogit** [bridgedb/docker#8]
We should state clearly which version of BDB we are packing with the given image, using the tag system.
Is this important or should we only worry with the latest version?

**Comment by egonw** [comment]
Use BridgeDb 2.2. Once 2.3 is out (not too distant, if things go well), then we can upgrade...

**Comment by egonw** [comment]
@nunogit, @marvinm2, you have a clear way forward now? Feel free to document the plan in a comment here.

**Comment by egonw** [comment]
BridgeDb 2.3.0 is released.

**Comment by marvinm2** [comment]
Updated for Bridgedb 2.3.0

**Comment by marvinm2** [comment]
Issue of versioning and keeping older versions:
I see that on dockerhub, many dockers have a flag with version indicator. For example https://hub.docker.com/r/library/centos/ 

If we would upload the latest version with this same flag, it would keep this there with the configurations of this version, so newer versions will just have new tags. Only need to make sure that the 'latest' version is really the latest version (the one that is pulled when you do not specify a tag). I read some things about this tag not being the same as others.
